Repository googleapis/java-shared-dependencies, pull requests merged in 2020-12, with the labels that each got.

#230 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: cla: yes, context: full

#234 deps: rollback gRPC to 1.33.1
  pom.xml
Labels: cla: yes

#242 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#244 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: cla: yes, context: full
