Repository googleapis/java-shared-dependencies, pull requests merged in 2020-09, with the labels that each got.

#135 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: cla: yes, context: full

#149 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: cla: yes, context: full

#147 feat: manage error-prone version
  pom.xml
Labels: automerge, cla: yes

#153 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: cla: yes, context: full

#154 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: cla: yes

#156 chore(ci): skip autorelease workflow on non-release PRs
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#157 chore(ci): verify autorelease release PR content has changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
