Repository googleapis/java-shared-dependencies, pull requests merged in 2020-05, with the labels that each got.

#32 ci: enable GitHub actions
  .github/workflows/ci.yaml
  .kokoro/build.bat
  synth.metadata
Labels: automerge, cla: yes, context: full

#34 docs: update CONTRIBUTING.md to include code formatting (#534)
  CONTRIBUTING.md
  synth.metadata
Labels: cla: yes, context: full

#40 feat: add more shared dependencies
  pom.xml
Labels: cla: yes

#44 feat!: remove mockito-core
  pom.xml
Labels: cla: yes

#49 feat!: remove certain test deps and autovalue
  pom.xml
Labels: automerge, cla: yes

#50 fix: remove grpc-testing since it's in grpc-bom
  pom.xml
Labels: automerge, cla: yes

#55 feat: add grpc-iam-v1 to keep version consistent w proto-iam-v1
  pom.xml
Labels: automerge, cla: yes

#59 feat: add core test classifier (needed by BQ)
  pom.xml
Labels: automerge, cla: yes
