Repository googleapis/java-shared-dependencies, pull requests merged in 2021-09, with the labels that each got.

#463 chore: use maven 3.8.1
  .github/workflows/downstream.yaml
Labels: automerge, cla: yes

#462 chore: use release-please to tag releases
  .github/release-please.yml
Labels: automerge, cla: yes

#461 ci: removing linkage-monitor from the required checks
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#468 chore: re-generated to pick up changes from synthtool
  .github/readme/synth.py
  .github/trusted-contribution.yml
  .github/workflows/ci.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, context: full

#476 deps: downgrade protobuf to 3.17.3 (not the latest 3.18.0)
  first-party-dependencies/pom.xml
Labels: automerge, cla: yes

#474 ci: upper-bound-check test
  .github/workflows/upper-bound-check.yaml
  upper-bound-check/pom.xml
Labels: cla: yes
