Repository googleapis/java-shared-dependencies, pull requests merged in 2021-04, with the labels that each got.

#322 deps: update guava to 30.1.1-android
  pom.xml
Labels: automerge, cla: yes

#325 build(java): skip javadoc tests during dependencies test
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, context: full

#332 fix: release scripts from issuing overlapping phases
  .kokoro/build.sh
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#341 feat: promote to 1.0.0
  .repo-metadata.json
Labels: automerge, cla: yes
