Repository googleapis/java-shared-dependencies, pull requests merged in 2021-07, with the labels that each got.

#397 chore: add pubsub and bigtable downstream dependency checks
  .github/workflows/downstream.yaml
Labels: automerge, cla: yes

#399 chore: remove All rights reserved clause from java.header
  java.header
  synth.metadata
Labels: automerge, cla: yes, context: full

#407 docs: we don't use this as a parent pom
  README.md
Labels: cla: yes

#409 chore: make pubsub downstream checks required
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes

#412 chore: migrate to google sonatype endpoint
  pom.xml
Labels: automerge, cla: yes
