Repository googleapis/java-shared-dependencies, pull requests merged in 2021-08, with the labels that each got.

#420 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes

#421 chore: configure initial java7 version
  .github/workflows/ci.yaml
  .github/workflows/downstream.yaml
Labels: automerge, cla: yes

#424 chore: removed java-spanner from required downstream check
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes

#423 deps: update guava to 30.1.1-jre
  pom.xml
Labels: cla: yes

#415 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, context: full

#436 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: cla: yes, context: full

#454 ci: remove linkage-monitor from required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes

#452 chore: enable release-trigger bot
  .github/release-trigger.yml
  synth.metadata
Labels: cla: yes, context: full
