Repository googleapis/java-shared-dependencies, pull requests merged in 2021-06, with the labels that each got.

#372 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#384 fix: Update dependencies.sh to not break on mac
  .kokoro/dependencies.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#389 feat: add grpc-gcp to dependencyManagement
  pom.xml
Labels: automerge, cla: yes

#391 fix: Add common httpclient and oauth dependencies
  pom.xml
Labels: cla: yes

#387 chore: minimize noise from build scripts
  .kokoro/coerce_logs.sh
  synth.metadata
Labels: cla: yes, context: full

#392 fix: Add `shopt -s nullglob` to dependencies script
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, context: full
