Repository googleapis/java-shared-dependencies, pull requests merged in 2022-11, with the labels that each got.

#911 ci: configure the protected branch
  .github/workflows/ci.yaml
  .github/workflows/downstream-native-image.yaml
  .github/workflows/downstream.yaml
  .github/workflows/version-check.yaml
Labels: size: l

#910 feat: next release from main branch is 3.1.0
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: size: s

#930 chore: upgrade native image downstream check to 22.3.0
  .github/workflows/downstream-native-image.yaml
Labels: size: xs
